name: clean_framework
description: Clean Architecture components library, inspired on the guidelines created by Uncle Bob.
version: 4.1.3
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework
screenshots:
  - description: 'Clean Framework'
    path: screenshots/clean-framework.png
topics:
  - clean-architecture
  - clean
  - framework
  - feature-flag

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

resolution: workspace

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0
  meta: '>=1.12.0 <2.0.0'
  stack_trace: '>=1.11.0 <2.0.0'
  uniform: ^2.0.6

dev_dependencies:
  clean_framework_test: ^0.5.4

  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
