name: clean_framework_http_example
description: An example app to demonstrate usage of clean_framework_http package.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  clean_framework: ^4.1.1
  clean_framework_http: ^0.4.4
  clean_framework_router: ^0.5.11
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_svg_image: ^1.1.0+1
  http_cache_sembast_store: ^1.0.0
  path_provider: ^2.1.4
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2

dev_dependencies:
  clean_framework_test: ^0.5.3-dev.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
