name: clean_framework_graphql
description: A wrapper around graphql to make it easier to use with clean_framework.
version: 0.4.4
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework/packages/clean_framework_graphql

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.32.0'

resolution: workspace

dependencies:
  clean_framework: ^4.1.3

  flutter:
    sdk: flutter
  gql: ^1.0.1
  graphql: ^5.2.3

dev_dependencies:
  clean_framework_test: ^0.5.4

  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^10.0.0
