name: clean_framework_example_rest
description: An example application to demonstrate usage of the clean_framework package with a REST api.
publish_to: none
version: 2.0.3+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animations: ^2.0.11
  clean_framework: ^5.0.0
  clean_framework_router: ^0.5.13
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_svg: ^2.0.10+1
  palette_generator: ^0.3.3+4
  uniform: ^2.0.6

dev_dependencies:
  clean_framework_test: ^0.5.4
  file: ^7.0.0
  flutter_test:
    sdk: flutter
  http: ^1.2.2
  icons_launcher: ^3.0.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/

icons_launcher:
  image_path: ../../../images/clean-framework.png
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
